### PR TITLE
Search bar and page

### LINKED ISSUE #9: Global Elements - Search
- no need to build search popup

### PR DESCRIPTION
**Pull request by nahbee10**
### Description

- added search bar to hero and header
- added search result page

### Type(s) of changes

- [ ] Bug fix
- [x] New feature
- [ ] Update to an existing feature

### Motivation for PR

- Closes #9 

### How Has This Been Tested?

Tested on local preview: https://uniswaplabs1730152595.zendesk.com/hc/en-us or https://uniswaplabs.zendesk.com/hc/en-us

### Applicable screenshots

https://www.loom.com/share/f9064d76f3354877a4a5b4793c5624d5?sid=ca38f5a4-71a3-464b-adeb-ee819278c961

### CODE REVIEW

**Comment by limsohee1002** [comment]
https://www.loom.com/share/eeab013f616b4deb8530197c19b20ebd?sid=a195cae4-1904-4620-90fa-fd6d2f212389
Unstyled dropdown is showing up

**Comment by limsohee1002** [comment]
Search seem to work well the x on search bar doesn't seem color within system

**Comment by nahbee10** [comment]
@limsohee1002 yeah those two elements are from native Zendesk search UI, and it's a bit hard to hack it since it disappears whenever I try to inspect it. I think it's doable to override the style but needs a bit more trick keeping the widget to inspect or dig into the document. I'll finish this here and add a ticket to address it.

**Comment by mokaymokay** [comment]
@nahbee10 I can help if you wanna pair

Screenshot 2024-11-08 at 12 12 45 PM

**Pull request merged**
